import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import TopNavbar from "@/components/ui/partials/topNavbar/TopNavbar";
import SideNavbar from "@/components/ui/partials/sideNavbar/SideNavbar";
import Footer from "@/components/ui/partials/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = React.HtmlHTMLAttributes<HTMLHtmlElement>;
export default function RootLayout({ children }: Props) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TopNavbar />
                <SideNavbar />
                <main className="w-full h-full">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
